# Jekyll configuration for GitHub Pages
title: "My Personal Site"
description: "A personal portfolio showcasing projects and blog posts."
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
