name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch

permissions:
  contents: write  # allow the workflow to push to the gh-pages branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all history for a clean push
          persist-credentials: true

      - name: Set up Node.js (required for the gh-pages action)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (if any)
        run: npm ci || true

      - name: Build site (if you have a build step)
        run: npm run build || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # publish the root of the repository
          # If you want to publish from a subdirectory, e.g., ./docs, change publish_dir accordingly
